import { loadData, saveData } from "./storage.js";
import { ensurePage, getAllPages, normalizeTitle, upsertPage } from "./pageManager.js";
import { getHomePage, isContentSpace } from "./constants.js";
import { getRoute, onRouteChange, routeToPage } from "./router.js";
import { closeMobileSidebar, renderCategoryPage, renderPage, renderSidebar, renderSpecialPage, showNotice, updateSpaceTabs } from "./ui.js";
let data=loadData(); let autosaveTimer; let currentRoute=getRoute(); let editing=false; let searchQuery="";
const els={searchInput:document.querySelector("#searchInput"),newPageBtn:document.querySelector("#newPageBtn"),randomPageBtn:document.querySelector("#randomPageBtn"),editBtn:document.querySelector("#editBtn"),deleteBtn:document.querySelector("#deleteBtn"),saveBtn:document.querySelector("#saveBtn"),cancelBtn:document.querySelector("#cancelBtn"),titleInput:document.querySelector("#titleInput"),spaceInput:document.querySelector("#spaceInput"),contentInput:document.querySelector("#contentInput"),sidebarToggle:document.querySelector("#sidebarToggle"),sidebar:document.querySelector("#sidebar")};
function effectiveSpace(){ return isContentSpace(currentRoute.space)?currentRoute.space:"study"; }
function render(){ currentRoute=getRoute(); updateSpaceTabs(currentRoute); renderSidebar(data,currentRoute,searchQuery); if(currentRoute.type==="special") renderSpecialPage(data,currentRoute.value); else if(currentRoute.type==="category") renderCategoryPage(data,currentRoute); else renderPage(data,currentRoute,editing); closeMobileSidebar(); }
function startEdit(){ if(currentRoute.type!=="page"||!isContentSpace(currentRoute.space)) return; editing=true; render(); }
function cancelEdit(){ editing=false; render(); }
function deleteCurrentPage(){ if(currentRoute.type!=="page") return; const {space,value:title}=currentRoute; if(title===getHomePage(space)){ showNotice("홈 문서는 삭제할 수 없습니다."); return; } if(!confirm(`정말 "${title}" 문서를 삭제할까요?`)) return; delete data.pages[`${space}::${title}`]; saveData(data); editing=false; showNotice("문서를 삭제했습니다."); routeToPage(space,getHomePage(space)); }
function saveCurrentPage(){ if(currentRoute.type!=="page") return; const oldSpace=currentRoute.space, oldTitle=currentRoute.value, nextSpace=els.spaceInput.value, nextTitle=normalizeTitle(els.titleInput.value), content=els.contentInput.value; try{ const page=upsertPage(data,oldSpace,oldTitle,nextSpace,nextTitle,content,{countRevision:true}); saveData(data); editing=false; showNotice("저장했습니다."); if(page.title!==oldTitle||page.space!==oldSpace) routeToPage(page.space,page.title); else render(); }catch(error){ showNotice(error.message||"저장에 실패했습니다."); } }
function autosaveCurrentPage(){ if(currentRoute.type!=="page"||!editing) return; const oldSpace=currentRoute.space, oldTitle=currentRoute.value, nextSpace=els.spaceInput.value, nextTitle=normalizeTitle(els.titleInput.value), content=els.contentInput.value; try{ const page=upsertPage(data,oldSpace,oldTitle,nextSpace,nextTitle,content,{countRevision:false}); saveData(data); if(page.title!==oldTitle||page.space!==oldSpace){ history.replaceState(null,"",`#/${page.space}/page/${encodeURIComponent(page.title)}`); currentRoute=getRoute(); } renderSidebar(data,currentRoute,searchQuery); }catch(error){ showNotice(error.message||"자동 저장 실패"); } }
function createNewPage(){ const space=isContentSpace(currentRoute.space)?currentRoute.space:"study"; const title=prompt(`${space==="profile"?"프로필":"개념"} 공간에 만들 새 문서 제목을 입력하세요.`); const normalized=normalizeTitle(title||""); if(!normalized) return; ensurePage(data,space,normalized); saveData(data); editing=true; routeToPage(space,normalized); }
function openRandomPage(){ const space=effectiveSpace(); const pages=getAllPages(data,space); if(!pages.length) return; const page=pages[Math.floor(Math.random()*pages.length)]; routeToPage(page.space,page.title); }
function setupAutosave(){ const trigger=()=>{ if(!editing) return; clearTimeout(autosaveTimer); autosaveTimer=setTimeout(()=>autosaveCurrentPage(),5000); }; els.contentInput.addEventListener("input",trigger); els.titleInput.addEventListener("input",trigger); els.spaceInput.addEventListener("change",trigger); }
function showFootnotePopup(anchor,text){ document.querySelector(".footnote-popup")?.remove(); const popup=document.createElement("div"); popup.className="footnote-popup"; popup.textContent=text; document.body.appendChild(popup); const rect=anchor.getBoundingClientRect(); popup.style.left=`${Math.max(12,Math.min(rect.left,window.innerWidth-340))}px`; popup.style.top=`${rect.bottom+window.scrollY+8}px`; setTimeout(()=>document.addEventListener("click",closeFootnotePopup,{once:true}),0); }
function closeFootnotePopup(event){ if(event.target.closest(".footnote-popup")||event.target.closest(".footnote-ref")) return; document.querySelector(".footnote-popup")?.remove(); }
function bindEvents(){ onRouteChange(()=>{ editing=false; render(); }); els.searchInput.addEventListener("input",e=>{ searchQuery=e.target.value; renderSidebar(data,currentRoute,searchQuery); }); els.newPageBtn.addEventListener("click",createNewPage); els.randomPageBtn.addEventListener("click",openRandomPage); els.editBtn.addEventListener("click",startEdit); els.deleteBtn.addEventListener("click",deleteCurrentPage); els.saveBtn.addEventListener("click",saveCurrentPage); els.cancelBtn.addEventListener("click",cancelEdit); els.sidebarToggle.addEventListener("click",()=>els.sidebar.classList.toggle("open")); window.addEventListener("velowiki:create-missing",event=>{ const space=event.detail?.space||effectiveSpace(); const title=normalizeTitle(event.detail?.title||""); if(!title) return; ensurePage(data,space,title); saveData(data); editing=true; routeToPage(space,title); }); document.addEventListener("click",event=>{ const tocLink=event.target.closest(".toc-link"); if(!tocLink) return; const section=document.getElementById(tocLink.dataset.section); if(section) section.scrollIntoView({behavior:"smooth",block:"start"}); }); document.addEventListener("click",event=>{ const ref=event.target.closest(".footnote-ref"); if(!ref) return; const id=ref.dataset.footnoteId; const item=document.querySelector(`[data-footnote-item="${CSS.escape(id)}"]`); if(item) showFootnotePopup(ref,item.textContent.trim()); }); document.addEventListener("keydown",event=>{ if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="s"&&editing){ event.preventDefault(); saveCurrentPage(); } }); }
function boot(){ if(!window.location.hash) routeToPage("study",data.settings?.homePage?.study||"홈"); bindEvents(); setupAutosave(); render(); }
boot();
