export const DEFAULT_DATA = {
  pages: {
    "study::홈": { title:"홈", space:"study", content:`# 홈\n\n내가 배우고, 이해하고, 살아남은 기록을 쌓는 개념 위키입니다.\n\n## 시작 문서\n\n- [[VeloWiki/사용법]]\n- [[Python/기초/조건문]]\n- [[수학/지수함수]]\n- [[프로필:공부를 선택한다는 것]]\n\n[[분류:메인]]`, categories:["메인"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 },
    "profile::프로필 홈": { title:"프로필 홈", space:"profile", content:`# 프로필 홈\n\n개인 성찰, 학습 동기, 감정 기록을 저장하는 공간입니다.\n\n- [[공부를 선택한다는 것]]\n\n[[분류:프로필]]`, categories:["프로필"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 },
    "study::VeloWiki/사용법": { title:"VeloWiki/사용법", space:"study", content:`# VeloWiki 사용법\n\n## 1. 링크\n\n\`[[문서명]]\`은 현재 공간 안에서 연결됩니다.\n\n다른 공간으로 연결하려면 다음처럼 씁니다.\n\n\`[[프로필:공부를 선택한다는 것]]\`\n\`[[개념:수학/지수함수]]\`\n\n## 2. 미디어\n\n\`{{image:https://picsum.photos/800/420|이미지 캡션}}\`\n\`{{youtube:dQw4w9WgXcQ}}\`\n\`{{link:https://ko.wikipedia.org/wiki/지수_함수|위키백과 - 지수 함수}}\`\n\n[[분류:도움말]]`, categories:["도움말"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 },
    "study::Python/기초/조건문": { title:"Python/기초/조건문", space:"study", content:`# 조건문\n\n조건문은 상황에 따라 다른 행동을 하게 하는 코드이다.\n\n\`\`\`python\nage = 18\nif age >= 20:\n    print("성인")\nelse:\n    print("미성년자")\n\`\`\`\n\n관련 문서: [[Python/기초/변수]], [[Python/실수/들여쓰기 오류]]\n\n[[분류:Python]]\n[[분류:코딩]]`, categories:["Python","코딩"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 },
    "study::수학/지수함수": { title:"수학/지수함수", space:"study", content:`# 지수함수\n\n{{정보상자\n|이름=지수함수\n|분류=수학\n|관련=[[수학/로그함수]], [[수학/초월함수]]\n|이미지=https://picsum.photos/400/260\n}}\n\n## 1. 개요\n\n지수함수는 지수에 미지수 x가 있는 함수이다.[^1]\n\n\`\`\`\nf(x) = a^x  (a > 0, a ≠ 1)\n\`\`\`\n\n{{image:https://picsum.photos/800/420|이미지 문법 테스트}}\n\n[^1]: 거듭제곱 자리에 정의역이 들어가기 때문에 일반적인 다항식과 다르다.\n\n[[분류:수학]]\n[[분류:함수]]`, categories:["수학","함수"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 },
    "profile::공부를 선택한다는 것": { title:"공부를 선택한다는 것", space:"profile", content:`# 공부를 선택한다는 것\n\n나는 남이 시켜서 하는 공부보다, 내가 선택해서 통과하는 공부를 원한다.\n\n## 핵심 문장\n\n> 고통받을 거라면, 그 고통은 내가 선택한다.\n\n관련 개념: [[개념:자율성]], [[개념:생존 서사]]\n\n[[분류:성찰]]\n[[분류:공부]]`, categories:["성찰","공부"], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), revisionCount:1 }
  },
  settings: { homePage: { study:"홈", profile:"프로필 홈" }, theme:"warm" }
};
